import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Grace Narez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/heart.png" />
      </Head>
      <main>
        <h1>Grace Narez</h1>
        <Image
          src="/me2.JPEG"
          alt="A proffesional picture of me"
          width={350}
          height={300}
        />
      </main>
      <div>
        <h2>contact me</h2>
        <div>
          <a href='https://github.com/gracenarez333'>github</a>
          <a href='https://www.linkedin.com/in/grace-narez-8b0498238/'>linkedin</a>
          <span>download my resume in </span>
          <a href='/GraceNarez.pdf' download='GraceNarezPDF'>pdf</a>
          <span> or </span>
          <a href='/GraceNarez2.txt' download='GraceNarezTXT'>plain text</a>
        </div>
      </div>
      <div>
        <h2>About Me</h2>
        <p>I am a charismatic and self-motivated software engineer, with a passion for solutions as well as learning from failure. The sensation of accomplishment through trial and error drives my passionate and open-minded approach to problem solving. I am malleable to and adaptable to any environment, where I can use my proven strategies to arrive at the needed solution.</p>
      </div>
      <div>
        <h2>Technologies</h2>
        <p>HTML5</p>
        <p>CSS</p>
        <p>JavaScript</p>
        <p>Python</p>
        <p>Mongoose</p>
        <p>Node</p>
        <p>Express</p>
        <p>Axios</p>
        <p>EJS</p>
        <p>Bootstrap</p>
        <p>SQL</p>
        <p>Postgres</p>
        <p>NoSQL</p>
        <p>Next.js</p>
        <p>Git</p>
        <p>Github</p>
        <p>Slack</p>
        <p>Object-oriented Programming</p>
        <p>Sequelize</p>
        <p>RESTful API</p>
      </div>
      <div>
        <div>
          <h3>Rat On A Scooter</h3>
          <p>Rat On A Scooter</p>
          <Image
            src="/ratonascooter.png"
            alt="Screenshot of Rat On a Scooter deployed"
            width={300}
            height={150}
          />
          <a href="https://github.com/gracenarez333/rat-on-a-scooter-sei-425">repo with deployed link here</a>
        </div>
        <div>
          <h3>Walkie Doggie</h3>
          <p>Walkie Doggie</p>
          <Image
            src="/walkiedoggie.png"
            alt="Screenshot of Walkie Doggie deployed"
            width={300}
            height={150}
          />
          <a href="https://github.com/gracenarez333/walkie-doggie-proj-2">repo with deployed link here</a>
        </div>
        <div>
          <h3>DettiPOS</h3>
          <p>DettiPOS</p>
          <Image
            src="/dettipos.png"
            alt="Screenshot of DettiPOS deployed"
            width={300}
            height={150}
          />
          <a href="https://github.com/gracenarez333/pos-client">repo with deployed link here</a>
        </div>
        <div>
          <h3>Star Wars Sheets</h3>
          <p>Star Wars Sheets</p>
          <Image
            src="/starwarssheets.png"
            alt="Screenshot of Star Wars Sheets deployed"
            width={300}
            height={150}
          />
          <a href="https://github.com/gracenarez333/star-wars-sheets">repo with deployed link here</a>
        </div>
      </div>
      <footer>
        <div>
          <div>
            <a href='https://github.com/gracenarez333'>github</a>
            <a href='https://www.linkedin.com/in/grace-narez-8b0498238/'>linkedin</a>
            <span>download my resume in </span>
            <a href='/GraceNarez.pdf' download='GraceNarezPDF'>pdf</a>
            <span> or </span>
            <a href='/GraceNarez2.txt' download='GraceNarezTXT'>plain text</a>
          </div>
          <p>© 2022 Grace Narez</p>
        </div>
      </footer>
    </div>
  )
}
