import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Grace Narez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/heart.png" />
      </Head>
      <div className='flex flex-col space-between bg-gradient-to-b from-purple-100 to-purple-500 items-center'>
        <div>
          <main className='flex flex-cols m-10 items-center'>
            <h1 className='text-purple-800 text-7xl p-3'>Grace Narez</h1>
            <Image
              className='rounded-lg'
              src="/me2.JPEG"
              alt="A proffesional picture of me"
              width={350}
              height={300}
            />
          </main>
        </div>
        <h2 className='text-purple-800 text-3xl'>download my resume</h2>
        <div className='m-10'>
          <div className='flex flex-row flex-wrap m-10 justify-center space-x-3'>
            <a className="hover:text-purple-700" href='/GraceNarez.pdf' download='GraceNarezPDF'>pdf</a>
            <span>or</span>
            <a className="hover:text-purple-700" href='/GraceNarez2.txt' download='GraceNarezTXT'>plain text</a>
          </div>
        </div>
        <h2 className='text-purple-800 text-3xl'>about me</h2>
        <div className='p-5 m-10 rounded-md items-center bg-white'>
          <p>I am a charismatic and self-motivated software engineer, with a passion for solutions as well as learning from failure. The sensation of accomplishment through trial and error drives my passionate and open-minded approach to problem solving. I am malleable to and adaptable to any environment, where I can use my proven strategies to arrive at the needed solution.</p>
        </div>
        <h2 className='text-purple-800 text-3xl'>technologies</h2>
        <div className='bg-gray-100 m-10 rounded-md'>
          <div className='flex flex-row flex-wrap m-10 justify-center space-x-3'>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>HTML5</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>CSS</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>JavaScript</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>Python</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>Mongoose</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>Node</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>Express</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>Axios</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>EJS</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>Bootstrap</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>SQL</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>Postgres</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>NoSQL</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>Next.js</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>Git</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>Github</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>Slack</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>Object-Oriented Programming</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>Sequelize</p>
            <p className='bg-purple-300 p-2 m-2 rounded-md hover:bg-purple-600'>RESTful API</p>
          </div>
        </div>
        <h2 className='text-purple-800 text-3xl'>projects</h2>
        <div className='flex flex-row flex-wrap m-10 justify-center bg-gray-100 rounded-md'>
          <div className='flex flex-col p-5 m-10 rounded-md items-center bg-purple-300'>
            <h3 className='text-purple-800'>Rat On A Scooter</h3>
            <Image
              className='rounded-md'
              src="/ratonascooter.png"
              alt="Screenshot of Rat On a Scooter deployed"
              width={300}
              height={150}
            />
            <p>repo with deployed link</p>
            <a className="text-purple-700" href="https://github.com/gracenarez333/rat-on-a-scooter-sei-425">here</a>
          </div>
          <div className='flex flex-col p-5 m-10 rounded-md items-center bg-purple-300'>
            <h3 className='text-purple-800'>Walkie Doggie</h3>
            <Image
              className='rounded-md'
              src="/walkiedoggie.png"
              alt="Screenshot of Walkie Doggie deployed"
              width={300}
              height={150}
            />
            <p>repo with deployed link</p>
            <a className="text-purple-700" href="https://github.com/gracenarez333/walkie-doggie-proj-2">here</a>
          </div>
          <div className='flex flex-col p-5 m-10 rounded-md items-center bg-purple-300'>
            <h3 className='text-purple-800'>DettiPOS</h3>
            <Image
              className='rounded-md'
              src="/dettipos.png"
              alt="Screenshot of DettiPOS deployed"
              width={300}
              height={150}
            />
            <p>repo with deployed link</p>
            <a className="text-purple-700" href="https://github.com/gracenarez333/pos-client">here</a>
          </div>
          <div className='flex flex-col p-5 m-10 rounded-md items-center bg-purple-300'>
            <h3 className='text-purple-800'>Star Wars Sheets</h3>
            <Image
              className='rounded-md'
              src="/starwarssheets.png"
              alt="Screenshot of Star Wars Sheets deployed"
              width={300}
              height={150}
            />
            <p>repo with deployed link</p>
            <a className="text-purple-700" href="https://github.com/gracenarez333/star-wars-sheets">here</a>
          </div>
        </div>
        <footer>
          <div className='flex flex-col flex-wrap items-center m-10'>
            <h2 className='text-purple-900 text-3xl'>contact me</h2>
            <div className='p-5 space-x-6'>
              <a className="hover:text-purple-900" href='https://github.com/gracenarez333'>github</a>
              <a className="hover:text-purple-900" href='https://www.linkedin.com/in/grace-narez-8b0498238/'>linkedin</a>
            </div>
            <div>
              <p className='text-purple-900'>© 2022 Grace Narez</p>
            </div>
          </div>
        </footer>
      </div>
    </div>
  )
}
